/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#454747",
        "tertiary": "#000000",
        "on-secondary-container": "#5f6161",
        "on-primary-fixed-variant": "#474646",
        "primary": "#000000",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed-dim": "#c6c6c7",
        "outline-variant": "#c4c7c7",
        "inverse-surface": "#303031",
        "on-background": "#1b1c1c",
        "secondary-container": "#dcdddd",
        "surface-variant": "#e3e2e2",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "on-tertiary-fixed": "#1d1b1a",
        "on-secondary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#c9c6c5",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f3f3",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#cac6c3",
        "secondary-fixed": "#e2e2e2",
        "surface-container-highest": "#e3e2e2",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-container": "#868381",
        "surface-container": "#efeded",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed-variant": "#484645",
        "tertiary-container": "#1d1b1a",
        "error-container": "#ffdad6",
        "background": "#fbf9f9",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "surface-tint": "#5f5e5e",
        "on-surface": "#1b1c1c",
        "surface": "#fbf9f9",
        "error": "#ba1a1a",
        "secondary": "#5d5f5f",
        "outline": "#747878",
        "surface-bright": "#fbf9f9",
        "on-surface-variant": "#444748",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad9",
        "tertiary-fixed": "#e6e1df",
        "inverse-primary": "#c9c6c5",
        "on-primary-container": "#858383"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-lg": "64px",
        "stack-md": "24px",
        "gutter": "24px",
        "unit": "4px",
        "stack-sm": "12px",
        "margin-desktop": "48px",
        "section-gap": "120px",
        "column-gap": "24px",
        "base": "8px"
      },
      fontFamily: {
        "display-xl": ["Bebas Neue"],
        "nav-label": ["Archivo Narrow"],
        "body-main": ["Archivo Narrow"],
        "headline-md": ["Bebas Neue"],
        "display-lg-mobile": ["Bebas Neue"],
        "display-lg": ["Bebas Neue"],
        "body-small": ["Archivo Narrow"],
        "headline-lg-mobile": ["Bebas Neue"],
        "headline-lg": ["Bebas Neue"],
        "button": ["Bebas Neue"],
        "body-md": ["Archivo Narrow"],
        "label-caps": ["Archivo Narrow"],
        "body-lg": ["Archivo Narrow"],
        "display-md": ["Bebas Neue"]
      },
      fontSize: {
        "display-xl": ["120px", { "lineHeight": "100px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "nav-label": ["13px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-main": ["16px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-md": ["40px", { "lineHeight": "44px", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "display-lg-mobile": ["56px", { "lineHeight": "52px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "display-lg": ["80px", { "lineHeight": "72px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "body-small": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["36px", {"lineHeight": "36px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "48px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "button": ["20px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "500"}],
        "display-md": ["64px", {"lineHeight": "60px", "letterSpacing": "0em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
